### ISSUE TITLE
Hourly usage charts should load at the first view with 2 days of visible data.

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#211]
Currently, hourly usage charts particularly for gas often don't load with 2 days of visible data, but  instead it tries to create a chart including a day when there is no data available. It  should default to perhaps the most recent day with data available, plus the same day a week previous for comparison, so 2 days are always visible. Otherwise for the first time user it is confusing why 2 dates  are not visible.

**Comment by ldodds** [comment]
Originally it was defaulting to the most recent day and the day before. So it should always have been displaying 2 days anyway, just within a limited window.

I think where the issue comes up is when there are missing readings. The gas feed in particular seems quite patchy, so there are odd missing days. In this case you might end up with only a single day displaying on the graph.

So I've changed the application so that it tries to always show 2 days. This will be:

* the day for which we have the latest readings
* the day 7 days previous to that. Or, if that's missing, the nearest available day

Hopefully that's a better default.
