### ISSUE TITLE
Updating data picking for Daily usage charts

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#238]
Allow users to choose week start date for the graphs, so can view weekly graphs across the whole data range. At the moment with poor up to date data, the daily usage charts are largely redundant, as you have no control over the date range, and you could end up looking at just one week, several weeks or months ago. Being able to specify the week start date would resolve this issue.

Children very confused by the current wording of 'latest' and 'previous'. Children commented that they thought they were saying the same thing. When you hover over a bar on the chart, the data information should give you the actual date, rather than just 'Friday' for example. Children very confused by what weeks they were looking at even when reminded frequently.

**Comment by ldodds** [comment]
I've completed these changes and they will be on the test server shortly. The page now matches the other graphs, the main difference is that here we're displaying a column chart with 1 or 2 weeks of data.


![uploads/a23a4bc7-60d8-40c1-9e01-33e88fca9044/Screenshot from 2017-08-31 15-38-54.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa23a4bc7-60d8-40c1-9e01-33e88fca9044%2FScreenshot+from+2017-08-31+15-38-54.png)

Happy to make further changes as required, please file as new issues.

To make the user interface consistent the page does operate a little differently. Rather than showing the last 7 days of data + the week before that it now shows:

- data for the current week (starting from Sunday)
- data for the previous week

Labels and chart summary should reflect this.

The calendar pickers also work slightly differently in this chart. Rather than selecting a single date, you're selecting a week worth of data. I've tweaked the picker user interface so as you hover over a week the whole week highlights and there's a message to indicate that you're choosing a week.

It's more natural to choose a week and look at 7 days, than pick a date and look at the preceeding 7 days which is what we had before. 

Other than that difference, the interface works the same, you can compare both types of supply, two dates, two meters, etc.
