### ISSUE TITLE
Hourly usage charts date picker range and bug

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#242]
Date picker should be restricted to the data availability range, otherwise children get confused by choosing dates with no data availability. It also prevents children from looking back in the distant past and then not remembering how to return to the present.

**Comment by ldodds** [comment]
Noting the bug here:

If you change the year in the date picker to say, 2000, then you'll see years 1990-2010. The only way to go to a more recent year is to reload/reset the page, click through the icons, or choose a year as close as possible, then try again. Interaction isn't immediately obvious!

A minimal fix would be to set the earliest selectable date to be earliest date we have the database. That will avoid ranges where there's no data.

Attempting to restrict selectable dates may require further customisation of the widget.
