### ISSUE TITLE
Add a Link box to the school home page linking to activity choice list.

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#248]
Full List of possible activities hard to find  from school home page (Not obvious that you have to look for it under About.. Activities) – children suggested you could have a box on school home page titled something like 'Choose some activities to save energy', which then links to the full list of activities, rather  than just recording an activity.

**Comment by ldodds** [comment]
To address this I've added a new page to help schools choose their next activity. This is now linked from the school homepage, rather than providing a direct link to the form.

The page has:

* a link to go straight to the form if the pupils just want to record an activity they've just completed
* links to the main activity list so they can look at all the activities before choosing
* some random suggested activities, one per category


![uploads/e2ce70cc-1ee4-4ca0-8905-b510c2b3306b/Screenshot from 2017-08-23 17-55-56.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe2ce70cc-1ee4-4ca0-8905-b510c2b3306b%2FScreenshot+from+2017-08-23+17-55-56.png)

We can improve suggestions later. At present there isn't a clear progression through the activities (or a sense of which ones can be repeated), so prompting them with a fresh, random set of suggestions each time seemed like a good default.

The links from the suggestions go to the full activity descriptions, as ideally they'll be reading about the activity and carrying it out before proceeding further with the application.
